# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nested_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nested_comment_text', models.CharField(max_length=1000)),
                ('task_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task_comment')),
            ],
        ),
    ]
